org: test1
space: dev
space-developer:
  ldap_users: []
  users: []
  ldap_group: ""
space-manager:
  ldap_users: []
  users: []
  ldap_group: ""
space-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
allow-ssh: false
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: true
enable-security-group: false
enable-remove-users: true
isolation_segment: test1-iso-segment
